
version: '3'
services:

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 80:80